<?php
$gLangDict=array(
    '奥丁号'=>'ODIN',
    '奥丁号拍卖交换工具'=>'PPk Swap Tool',
    '[演示]'=>'[DEMO！]',
    '拍卖&交换'=>'Auction&Swap',
    '拍卖'=>'Auctions',
    '更多拍卖记录'=>'More auctions',
    '求购'=>'Wants',
    '更多求购记录'=>'More wants',
    '帮助'=>'Help',
    '查看竞拍'=>'Auctions',
    '发布拍卖'=>'New auction',
    '查看求购'=>'Wants',
    '我要求购'=>'New want',
    '我的帐号'=>'My account',
    '消息'=>'Messages',
    '以奥丁号登录'=>'Login as ODIN',
    '注册新用户'=>'Register',
    '注册奥丁号'=>'Register',
    '拍卖奥丁号'=>'Auction',
    '排序'=>'Sort',
    '最新报价'=>'Last bid',
    '状态'=>'Status',
    '拍卖方'=>'Seller',
    '无底价'=>'No reserve price',
    '报价中'=>'Bidding',
    '达成意向'=>'Accepted',
    '已付款'=>'Paid',
    '拍卖方已发出过户'=>'Transfered',
    '求购中'=>'Wanting',
    '已结束'=>'Closed',
    '交易取消'=>'Canceled',
    '到期确拍中'=>'Confirming',
    '到期流拍'=>'No bid',
    '等待确拍超时而流拍'=>'No confirmed',
    '等待支付超时而流拍'=>'Not paid',
    '已完成'=>'Finished',
    '未中标'=>'Lost',
    '约'=>'About',
    '元'=>'CNY',
    '还有'=>'Remain',
    '天多'=>'days',
    '天'=>'day',
    '小时'=>'hour',
    '分钟'=>'minutes',
    '秒'=>'seconds',
    '天前'=>'days ago',
    '小时前'=>'hours ago',
    '分钟前'=>'minutes ago',
    '秒前'=>'seconds ago',
    '上一页'=>'Prev',
    '下一页'=>'Next',
    '当前为第'=>'Current is page ',
    '页'=>'',
    '风险提示：此公测工具仅提供自主、点对点互换奥丁号(ODIN)的信息聚合展示，不提供居中担保和裁判规则，无法保证交易双方的真实意愿和实际行为，请自主决定、自担风险。'=>'Risk Warning: This public beta tool only provides informations that are autonomous, point-to-point exchanges of ODIN names.  This tool can not guarantee the true will and actual behavior of both parties! Please use at your own risk.',
    '演示环境，仅供测试体验，不能用作实际资产交易！！！' => 'Risk Warning: This is a demo only for testing ! NO for the real transaction !',
    '请阅读帮助详细了解，谨慎操作。'=>'Please read the help for details and caution!',
    '快速查询'=>'Quick Search',
    '尾数6和8'=>'Ends with 6/8',
    '不带4'=>'No number 4',
    '类似666'=>'Like 666',
    '类似123'=>'Like 123',
    '新发布'=>'Last auctions',
    '最近报价'=>'Last bids',
    '自定义'=>'User define',
    '推荐标题'=>'Subject',
    '起始报价'=>'Reserve price',
    '详细说明'=>'Remark',
    '拍卖状态'=>'Auction status',
    '竞拍结束时间'=>'End time',
    '长期'=>'No deadline',
    '拍卖方身份标识'=>'Seller ID',
    '已参拍报价列表'=>'Bids',
    '报价'=>'Price',
    '时间'=>'Time',
    '报价方'=>'Bidder',
    '注意：出于资金安全，建议采用拍卖方身份标识对应钱包地址作为转账地址，并仔细核对币种数额。不要随意向通过微信、Telegram等聊天工具联系时提供的地址转账。'=>'Note: For security, it is recommended to use the seller ID related wallet address as the transfer address, and check the tranfer amount carefully. Do not transfer money to the address provided when you contact a chat tool such as WeChat or Telegram.',
    '等待拍卖方确拍,'=>'Pending confirm of seller, ',
    '等待报价方支付,'=>'Pending pay by bidder, ',
    '超时将流拍'=>' then expired',
    '获取报价列表出错，请稍候再试！'=>'There is an error getting the quote list, please try again later!',
    '我要报价'=>'I bid',
    '你的奥丁号'=>'Your ODIN',
    '使用支持奥丁号的APP自主验证身份'=>'Login with the APP supports ODIN',
    '使用支持奥丁号的APP扫码登录（如PPk浏览器、微信等）'=>'Scan with the APPs that support ODIN such as PPkBrowser,MicroMsg etc. ',
    '注：需升级到PPkBrowser安卓版0.305以上版本，'=>'Note: please upgrade to PPkBrowser Android version 0.305 or later,',
    '请点击阅读这里的操作说明安装和使用。'=>'Please click here to read the guide.',
    '更多信息，'=>'And more',
    '可以参考奥丁号和PPk开放协议的资料进一步了解。'=>'Further information can be found here.',
    '使用比原钱包地址登录'=>'Login with Bytom wallet address',
    '你的比原地址'=>'Your Bytom address',
    '请输入有效的比原钱包地址（以b起始）'=>'Please enter a valid Bytom wallet address (starting with b)',
    '体验登录'=>'Quick login',
    '欢迎使用比原地址登录体验测试！'=>'Welcome! You had logon with the Bytom address.',
    '您现在就可以参与竞拍报价了。\n如需发起拍卖自己拥有的奥丁号资产，需使用PPk应用并进行身份验证。'=>'Now you only can bid in existed auction. To add an auction of your owned ODIN assets, you need to use the PPk android APP.',
    '请先设置所要使用的奥丁号！'=>'Please set the ODIN which you want to use first!',
    '获得的用户信息有误!'=>'The user information is incorrect!',
    '无法获取对应用户信息！'=>'Unable to get the user information!',
    '无法签名指定资源！'=>'Unable to sign the specified resource!',
    '请检查确认该资源已配置有效的验证密钥。'=>'Please check that the resource has a valid authentication key configured.',
    '获得的签名信息有误'=>'The signature is incorrect!',
    '验证用户身份成功'=>'Verified user identity successful',
    '用户身份标识签名验证未通过！'=>'User ID signature verification failed!',
    '验证签名信息有误!'=>'The signature is incorrect!',
    '指定用户标识尚未设置身份密钥，无法验证登录！'=>'The specified user ID has not been set up with an identity key and cannot be verified!',
    '请输入有效的用户奥丁号，如'=>'Please enter a valid user ODIN, such as',
    '身份标识'=>'User ID',
    '对应PPk协议URI'=>'Full PPk URI',
    '电子邮件'=>'Email',
    '创建时间'=>'Creation time',
    '拥有者主钱包地址'=>'Register wallet address',
    '关联钱包地址'=>'More binded wallet addresses',
    '修改'=>'Modify',
    '设置'=>'Set',
    '发布拍卖总次数'=>'Total auctions added',
    '参与报价总次数'=>'Total bids',
    '退出登录状态'=>'Logout',
    '主钱包地址所注册数字资产'=>'The digital assets registered by the main wallet address',
    '短标识'=>'Short ODIN',
    '完整标识'=>'Full ODIN',
    '重新发起拍卖'=>'Readd it',
    '体验帐户，不能发起拍卖'=>'Experience account, can not add new auction',
    '说明'=>'readme',
    '报价参拍'=>'New bid',
    '标的奥丁号'=>'Auctioning ODIN',
    '参拍用户身份'=>'Bidder ID',
    '填写我的报价信息'=>'Fill my bid',
    '出价币种'=>'Coin type',
    '我的钱包地址'=>'My wallet address',
    '尚未关联设置对应的钱包地址'=>'The corresponding wallet address has not been setted',
    '请点击这里设置'=>'Set it now',
    '我的报价'=>'My offer',
    '备注说明'=>'Remark',
    '可以填写报价方自己的可选联系方式如Email/微信/Telegram等。'=>'You can fill in your contact information such as Email / WeChat / Telegram.',
    '注意：报价内容一旦提交，将不能更改和撤销，请仔细填写！'=>'Note: Once the form submitted, it cannot be changed and revoked. Please be carefully!',
    '提交报价'=>'Submit',
    '注意：报价一旦提交，将不能更改和撤销，确认提交吗？'=>'Note: Once the form submitted, it cannot be changed and revoked.\nAre you sure to submit?',
    '当前用户是直接登录的比原地址，需提供一个有效BTC地址（1起始），用于报价被接受后接收奥丁号'=>'Current user is logged in with a Bytom address, and a valid BTC address (starts with 1) is required to receive the ODIN asset after the bid is accepted.',
    '点击这里查看'=>'Click here to review',
    '对应奥丁号'=>'The ODIN',
    '的报价已提交。'=>"'".'s bid had been saved.',
    '报价单详情'=>'Bid detail',
    '报价金额'=>'Offered price',
    '我的钱包地址'=>'My wallet address',
    '报价方钱包地址'=>'Bidder wallet address',
    '注意：尚未关联设置钱包地址'=>'Note: The corresponding wallet address has not been setted',
    '拍卖方钱包地址'=>'Seller wallet address',
    '接受报价'=>'Accept it',
    '已转移资产拥有权'=>'Transfered the ownership to bidder',
    '现在付款给拍卖方'=>'Pay to the seller',
    '确认收到资产，交易完成'=>'Confirm finished',
    '相关链上存证信息'=>'Proof informations on the blcockchain',
    '拍卖方接受报价的记录'=>'The seller had accepted the specific bid',
    '查看对应的链上存证信息'=>'View the original transaction by the blockchain explorer',
    '报价方确认付款的记录'=>'The bidder had paid to seller',
    '点击返回所属拍卖纪录'=>'Back to the auction ',
    '原始交易ID'=>'Original TXID',
    '处理拍卖交易'=>'Processing auction ',
    '待存证到链上的信息'=>'Proof to be saved on the chain',
    '确认并发送到'=>'Confirm and broadcast to ',
    '链上公开存证'=>' for proof',
    '注：1.确认报价或支付并存证到链上会花费若干交易费用。'=>'Note:1.Accepting bid or paying by the chain will cost a few transaction fees.',
    '2.出于资金安全，建议采用拍卖方身份标识对应钱包地址作为转账地址，并仔细核对币种数额。不要随意向通过微信、Telegram等聊天工具联系时提供的地址转账。'=>'2.For security, it is recommended to use the seller ID related wallet address as the transfer address, and check the tranfer amount carefully. Do not transfer money to the address provided when you contact a chat tool such as WeChat or Telegram.',
    '等待拍卖方确拍'=>'Pending confirm of seller ',
    '3.在通过BTC链进行奥丁号转移过户时，卖方在发出转移和买方在确认转移时，需留意调整所使用奥丁号管理工具的矿工费用，建议在BTC交易拥堵时提高到10000聪或更好水平，以得到比较快的确认。'=>'',
    '已发出的存证交易编号'=>'Broadcasted transaction for proof',
    '自行更新存证交易记录'=>'Update the transaction ID by self',
    '交易已确认'=>'Transaction had been confirmed.',
    '的拍卖交易状态已更新。'=>' The auction status had been updated.',
    '已中标'=>'Won',
    '该拍卖已取消'=>'Canceled',
    '参拍奥丁号'=>'Bidded',
    'English'=>'中文',
    '访问该币种的PPk网址主页（需要使用PPkBrowser安卓应用0.3.5以上版本）'=>'View the PeerWebSite',
    '发布新拍卖'=>'New auction for ',
    '管理者比特币地址'=>'Admin BTC address',
    '附注名称'=>'Title',
    '配置权限'=>'Authority',
    '注册者比特币地址'=>'Register BTC address',
    '发布者身份标识'=>'Seller ID',
    '如该ODIN标识可对应的靓号名称举例'=>'For example: the best alias name of this ODIN ID ',
    '不填写或输入0表示无底价拍卖'=>'Not fill in or enter 0 for no reserve price',
    '可以填写对该数字资产的描述说明、拍卖方的联系方式如Email/微信/Telegram等。'=>'You can fill in the description of the digital asset, the contact information of the seller, such as Email/WeChat/Telegram.',
    '注意：拍卖内容一旦提交，将不能更改，请谨慎操作！'=>'Note: Once the form submitted, it cannot be changed and revoked. Please be carefully!',
    '竞拍持续时间'=>'Auction duration',
    '周'=>'week',
    '月'=>'month',
    '年'=>'year',
    '注意：拍卖内容一旦提交，将不能更改，确认提交吗？'=>'Note: Once the form submitted, it cannot be changed and revoked.\nAre you sure to submit?',
    '马上发布'=>'Submit',
    '的拍卖信息已发布。'=>"'".'s auction had been saved.',
    '全部显示'=>'All',
    '留言建议'=>'Leave Message',
    '请稍候'=>'Waiting',
    '我'=>'Me',
    '最新回应'=>'Last reply',
    '求购方'=>'Wanter',
    '查看详情'=>'View detail',
    '开始求购'=>'Start',
    '开始拍卖'=>'Start',
    ''=>'',
    ''=>'',
    ''=>'',
);

            
function getLang($cn_str){
    global $gLangDict;
    if(array_key_exists($cn_str,$gLangDict) )
        return $gLangDict[$cn_str];
    else
        return $cn_str;
}


/*

<?php echo getLang('');?>

',getLang(''),'

'.getLang('').'

*/